[package]
name = "shine-service"
version = "0.1.0"
authors = ["gzp-crey <z.p.gaal@google.com>"]
edition = "2021"


[features]
default = ["ot_jaeger", "ot_zipkin", "ot_app_insight"]

ot_jaeger = ["opentelemetry-jaeger"]
ot_zipkin = ["opentelemetry-zipkin"]
ot_app_insight = ["reqwest", "opentelemetry-application-insights"]

[dependencies]
log = "0.4"
thiserror = "1.0"
config = "0.13"

serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

time = "0.3"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.3", features = ["v4", "serde"] }
base64 = "0.21"
hex = "0.4"
ring = "0.16"

futures = "0.3"
async-trait = "0.1"
tokio = {version = "1.27", features = ["macros", "rt-multi-thread", "signal"] }
reqwest = { version = "0.11", optional = true }

azure_core = { version = "0.12" }
azure_identity = { version = "0.12" }
azure_security_keyvault = { version = "0.12" }

tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-opentelemetry = "0.19"
opentelemetry = { version = "0.19", features = ["rt-tokio"] }
opentelemetry-semantic-conventions = "0.11"
opentelemetry-jaeger = { version = "0.18", features = ["rt-tokio"], optional = true }
opentelemetry-zipkin = { version ="0.17", features = ["reqwest-client"], default-features = false, optional = true }
opentelemetry-application-insights = { version = "0.25", optional = true }

axum = "0.6"
axum-extra = { version = "0.7", features = ["cookie", "cookie-signed", "cookie-private"] }
axum-tracing-opentelemetry = "0.11"

shine-macros = { path = "../shine-macros", version = "0.1.0" }